<a href="https://colab.research.google.com/github/Sinchiguano/ai_googleColab/blob/main/pythonOnGoogleColab_Lecture9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print('cesar sinchiguano')
#https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb#scrollTo=1L4Am0QATgOc

cesar sinchiguano


In [ ]:
!python --version 

Python 3.10.11


TIPOS DE DATOS BÁSICOS
Números. ENTEROS Y DECIMALES

In [ ]:
ejemplo1=2
print('-------')
print(ejemplo1)
print('Producto ejemplo1*ejemplo: \n{:.3f} '.format(ejemplo1*ejemplo1))
print(ejemplo1-ejemplo1)
print(ejemplo1+ejemplo1)
print(ejemplo1**ejemplo1)
ejemplo1+=3
print(ejemplo1)
ejemplo1*=2
print(ejemplo1)
print(type(ejemplo1))
ejemplo1*=10.5
print(type(ejemplo1))
print(type(ejemplo1),ejemplo1**ejemplo1,ejemplo1*3)

-------
2
Producto ejemplo1*ejemplo: 
4.000 
0
4
4
5
10
<class 'int'>
<class 'float'>
<class 'float'> 1.6783263083479556e+212 315.0


Booleans

In [ ]:
mask1=True
mask2=False
resultAnd=mask1 and mask2
print(resultAnd)
print(mask1 or mask2)
print(not mask1)
print(not mask2)

False
True
False
True


String

In [ ]:
lastName='sinchiguano'
print(lastName.capitalize())
print(lastName.upper())
print(lastName.lower())
print(len(lastName))
message='Hello,'
print(message+' '+lastName)

Sinchiguano
SINCHIGUANO
sinchiguano
11
Hello, sinchiguano


Containers

In [ ]:
listNumbers=[1,2,3,4,5,6]
import numpy as np
listLastNameIndex=np.arange(len(lastName))
print(listLastNameIndex)
print(type(listLastNameIndex))
listLastNameIndex=np.arange(10)
print(listLastNameIndex)
print(type(listLastNameIndex))
someList=['cesar',13,True]
print(someList)
print(someList[0])
someList[1]=45
print(someList)
someList.append('one')
someList.append(1)
print(someList)
test=someList.pop()
print(test)
print(someList.index('one'))
print(someList[3])
import random
# Generate a random list of floating-point numbers
random_list = [random.randint(0, 100) for _ in range(10)]
print(random_list)
print(type(random_list))
random_list.sort()
print(random_list)

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
['cesar', 13, True]
cesar
['cesar', 45, True]
['cesar', 45, True, 'one', 1]
1
3
one
[35, 57, 56, 28, 79, 49, 54, 41, 87, 55]
<class 'list'>
[28, 35, 41, 49, 54, 55, 56, 57, 79, 87]


Loops: You can loop over the elements of a list like this 

In [ ]:
animals=['cat','dog','monkey']
print(animals[1:3])
numbers=list(range(20))
print(numbers)
print(numbers[8:15])
print(numbers[:8])
numbers[1:3]=[8,9]
print(numbers)
print(numbers[:-1])

for animal in animals:
  print('Animal: {}'.format(animal.upper()))
indices=[i for i in range(len(animals))]
print(indices)

indexNumbers=list()
for i in range(len(numbers)):
  indexNumbers.append(i)
print(indexNumbers)


for index, animal in enumerate(animals):
  print('%d  %s'%(index,animal))

['dog', 'monkey']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[8, 9, 10, 11, 12, 13, 14]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 8, 9, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 8, 9, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Animal: CAT
Animal: DOG
Animal: MONKEY
[0, 1, 2]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
0  cat
1  dog
2  monkey


In [ ]:
sample=list(range(6))
print(sample)
squareNumber=list()
for i in sample:
  squareNumber.append(i**2)
print(squareNumber)

[0, 1, 2, 3, 4, 5]
[0, 1, 4, 9, 16, 25]


DICTIONARIES

In [ ]:
d={'cat':'cute','dog':'clever'}
print(d['cat'])
print('cat' in d)
d['fish']='wet'
my_dict = {"name": "John", "age": 30, "city": "New York"}
for key in my_dict:
  print('Key: {} - Value: {}'.format(key,my_dict[key]))
print('----------------')
for key, value in d.items():
  print('Key: {} - Value: {}'.format(key,value))


cute
True
Key: name - Value: John
Key: age - Value: 30
Key: city - Value: New York
----------------
Key: cat - Value: cute
Key: dog - Value: clever
Key: fish - Value: wet


Functions

In [ ]:
myList=list()
myList.append(-1)
myList.append(0)
myList.append(1)
print(myList)

def checkSign(number):
  if (number<0):
    print('The number is negative: {}'.format(number))
  elif (number>0):
    print('The number is positive: {}'.format(number))
  else:
    print('The number is cero: {}'.format(number))


# checkSign(myList[2])

for index, item in enumerate(myList):
  print(checkSign(item))


[-1, 0, 1]
The number is negative: -1
None
The number is cero: 0
None
The number is positive: 1
None


In [ ]:
def changeToUpperCase(name, flag=True):
  if flag:
    print(name.upper())
  elif flag==False:
    print(name.lower())

nameList=['juan','carlos','veronica','roberto']

# changeToUpperCase(nameList[0],False)
# changeToUpperCase(nameList[0],True)

print('-----------------')

import random 

print(random.choice([False, True]))

for name in nameList:
  controlFlag=random.choice([True,False])
  changeToUpperCase(name,controlFlag)



-----------------
False
JUAN
carlos
veronica
roberto


Class

The syntax for defining classes in Python is straightforward.

Attributes (variables)
Methods (functions)

All classes have a function called __init__(), which is always executed when the class is being initiated.

In [ ]:
class Person():
  def __init__(self, name, age):
    self.name=name
    self.age=age
  
p1=Person('juan',12)
p2=Person('Lucas',13)

p4=Person('Pepe',18)
p3=Person('Liam',15)

print(p1.name, ' - ',p1.age)
print(p4.name, ' - ',p4.age)



juan  -  12
Pepe  -  18


In [ ]:
class myClass:
  def __init__(self, name):
    self.name=name
  

  def message(self):
    print('Hello, {}'.format(self.name))

  def upperCase(self, flag=False):
    if flag:
      print('Hello, {}'.format(self.name.upper()))
    else:
      print('Hello, {}'.format(self.name))


ob1=myClass('Peter')
ob2=myClass('Juan')

print('-------')

ob1.upperCase(True)
ob2.upperCase(False)


-------
Hello, PETER
Hello, Juan


CLASSES

In [ ]:
class greetings():
  def __init__(self, name):
    self.name=name
 
  def hello(self,flag):
    if flag:
      print('HELLO, '+self.name.upper())
    elif not flag:
      print('Hello, '+self.name)

object1=greetings('Cesar')
object2=greetings('Juan')
object3=greetings('Carlos')

object3.hello(False)
object3.hello(True)

Hello, Carlos
HELLO, CARLOS


Numpy

In [ ]:
import numpy as np


a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

print('*****************')
b=np.array([[1,2,3],[1,3,5]])
print(type(b))
print(b.shape)
print(b)




<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
*****************
<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [1 3 5]]


Numpy also provides many functions to create arrays

In [ ]:
import numpy as np

a=np.zeros((2,3))
print(a)
b=np.ones((3,5))
print(b)
c=np.full((3,3),8)
print(c)
d=np.eye(5)
print(d)
# Create a 2D array with shape (3, 3) filled with random values between 0 and 1
# normal distribution 
e=np.random.rand(3,3)
print(e)
# numpy.random.randn(d0, d1, ..., dn):
# Generates an array of random numbers from a standard normal distribution (mean=0, standard deviation=1).
f=np.random.randn(4,5)
print(f)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.83577674 0.46607493 0.92161798]
 [0.2531174  0.74847482 0.58369438]
 [0.83251242 0.25384291 0.60687874]]
[[ 0.19557571 -0.17151519  1.39434055  0.50118555  1.11803946]
 [-0.5164746  -1.80605299 -0.27653736  0.26132641  0.2199152 ]
 [ 1.09573443 -0.41113504  0.59142538 -0.18994837 -0.22903234]
 [-0.05397989 -0.31581645 -2.17935774  0.37461948  0.83274782]]


Array indexing

In [ ]:
import numpy as np


# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)
print('a[2,2] : ',a[2,2])

print(f'a[2,2] : {a[2,2]}')

# b=a[:2,1:3]

# # Create a 3-dimensional array
# arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# print(arr3.ndim)  # Output: 3
# print(arr3)
# print(arr3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
a[2,2] :  11
a[2,2] : 11
